name: cuba_weather_redcuba_dart
description: Dart client for www.redcuba.cu weather API. Given a municipality in Cuba, weather data on the municipality is obtained.
version: 2.0.0
homepage: https://github.com/cuba-weather/cuba-weather-redcuba-dart

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  http: ^0.12.0
  cuba_weather_municipality_dart: ^0.1.2
