name: cuba_weather_redcuba_dart
description: Application programming interface of the Cuba Weather project for [www.redcuba.cu](https://www.redcuba.cu) implemented in Dart.
version: 2.1.0
homepage: https://github.com/cuba-weather/cuba-weather-redcuba-dart

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  http: ^0.12.0
  cuba_weather_municipality_dart: ^0.1.3
